# gcloud builds submit --config=cloudbuild.yaml .
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |-
        ./deploy.sh \
          --source-project '${_PJID_SRC}' \
          --target-project '${_PJID_TGT}' \
          --cdc-processed-dataset '${_DS_CDC}' \
          --raw-landing-dataset '${_DS_RAW}' \
          --target-reporting-dataset '${_DS_REPORTING}' \
          --target-models-dataset '${_DS_MODELS}' \
          --location '${_LOCATION}' \
          --mandt '${_MANDT}' \
          --sql-flavour '${_SQL_FLAVOUR}' \
            '${_VIEWS_DIR}'
logsBucket: "gs://$_GCS_BUCKET"
timeout: 7200s
substitutions:
  _VIEWS_DIR: src/views
  _MANDT: "800"
  _TEST_DATA: "false"
  _LOCATION: "US"
  _DS_REPORTING: "SAP_REPORTING"
  _DS_MODELS: "SAP_ML_MODELS"
  _SQL_FLAVOUR: "ECC"
options:
  substitution_option: "ALLOW_LOOSE"
